# Generated by Django 6.0.7 on 2026-08-09 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('summary', models.TextField(blank=True, verbose_name='Tóm tắt ngắn')),
                ('content', models.TextField(verbose_name='Nội dung bài viết')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Ảnh đại diện')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('is_published', models.BooleanField(default=True, verbose_name='Công khai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Danh sách bài viết',
                'ordering': ['-created_at'],
            },
        ),
    ]
