# Generated by Django 6.0.7 on 2026-08-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techx', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(db_index=True, default='TechX', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='key',
            field=models.CharField(db_index=True, help_text='VD: Kết nối, Pin, Trọng lượng', max_length=100),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='productspecification',
            unique_together={('product', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'color_name', 'spec_option')},
        ),
    ]
